# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cf74af5847571e4ec5547f6aa3b822aea50f6b12b73f838ef4beb8148a29ca938f261cd1a2458447847fcd38acb36c679fb4104783237ab6e53f941873bac4e

test:
  secret_key_base: 893d6f4dc2c73d45b384dc8249d6bfaa87380c6ab493af18cef69e47c0b22ac88d5f6698bceae89ed1ffc7b9364570702f916c66c599947c175176492289bad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
